'$include:'Console/emptyKey.bi'
'$include:'Console/newLine.bi'
'$include:'Console/read.bi'
'$include:'Console/readKey.bi'
'$include:'Console/readLine.bi'
'$include:'Console/write.bi'
'$include:'Console/writeLine.bi'
