const REGISTERCOUNT = 4
const INDEXCOUNT = 2
const FLAGCOUNT = 4

const ACCUREGISTER = 0

const INDEXREGISTER = 1
const XREGISTER = 1
const YREGISTER = 2

const STACKPOINTER = 3

'const RESERVEDREGISTER1 = 2
'const RESERVEDREGISTER2 = 3

const ZEROFLAG = 0
const OVERFLOWFLAG = 1
const SIGNFLAG = 2
const CARRYFLAG = 3
