'$include:'./Application/Options.bi'
'$include:'./Application/Constants.bi'
'$include:'./Application/globalVariables.bi'
'$include:'./Application/localVariables.bi'
'$include:'./Application/Main.bi'

'$include:'./Application/Exceptions.bi'
'$include:'./Application/Keywords.bi'
'$include:'./Application/Results.bi'

'$include:'./Cpu/BytesToWord.bi'
'$include:'./Cpu/clearFlag.bi'
'$include:'./Cpu/debug.bi'
'$include:'./Cpu/execute.bi'
'$include:'./Cpu/flagIf.bi'
'$include:'./Cpu/run.bi'
'$include:'./Cpu/setFlag.bi'

'$include:'./Hex/fromByte.bi'
'$include:'./Hex/fromWord.bi' 

'$include:'./Memory/correct.bi'
'$include:'./Memory/create.bi'
'$include:'./Memory/dump.bi'
'$include:'./Memory/isCreated.bi'
'$include:'./Memory/peek.bi'
'$include:'./Memory/poke.bi'
'$include:'./Memory/release.bi'

'$include:'./Opcode/ClearFlag.bi'
'$include:'./Opcode/Halt.bi'
'$include:'./Opcode/JumpByte.bi'
'$include:'./Opcode/JumpWord.bi'
'$include:'./Opcode/LoadRegisterAddress.bi'
'$include:'./Opcode/LoadRegisterValue.bi'
'$include:'./Opcode/NoOperation.bi'
'$include:'./Opcode/SetFlag.bi'
'$include:'./Opcode/Stop.bi'
'$include:'./Opcode/StoreRegisterAddress.bi'
'$include:'./Opcode/TransferFromAccu.bi'
'$include:'./Opcode/TransferIntoAccu.bi'
